"""baseline: 冻结当前schema

Revision ID: 55198abfb01f
Revises:
Create Date: 2026-08-14 19:07:01.900917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55198abfb01f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('ai_instructions', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_audit_logs_action'), 'mcp_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_created_at'), 'mcp_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_id'), 'mcp_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_novel_id'), 'mcp_audit_logs', ['novel_id'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_target_type'), 'mcp_audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_user_id'), 'mcp_audit_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('worldview', sa.Text(), nullable=True),
    sa.Column('rag_lifecycle_id', sa.String(length=32), nullable=False),
    sa.Column('rag_revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rag_lifecycle_id')
    )
    op.create_index(op.f('ix_novels_id'), 'novels', ['id'], unique=False)
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_index(op.f('ix_novels_user_id'), 'novels', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rag_lifecycle_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('chapter_number > 0', name='ck_chapters_number_positive'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number', name='uq_chapters_novel_number'),
    sa.UniqueConstraint('rag_lifecycle_id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('character_arc', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.String(length=20), nullable=True),
    sa.Column('first_appearance_chapter', sa.Integer(), nullable=True),
    sa.Column('last_appearance_chapter', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_table('novel_outlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('estimated_word_count', sa.Integer(), nullable=True),
    sa.Column('actual_word_count', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.String(length=50), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('key_plot_points', sa.JSON(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['novel_outlines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novel_outlines_id'), 'novel_outlines', ['id'], unique=False)
    op.create_table('plot_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chapter_start', sa.Integer(), nullable=True),
    sa.Column('chapter_end', sa.Integer(), nullable=True),
    sa.Column('position_in_story', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('emotional_impact', sa.String(length=50), nullable=True),
    sa.Column('plot_function', sa.String(length=100), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('affected_settings', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('consequences', sa.JSON(), nullable=True),
    sa.Column('development_stage', sa.String(length=50), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_elements_id'), 'plot_elements', ['id'], unique=False)
    op.create_table('story_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('timeline_point', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('story_day', sa.Integer(), nullable=True),
    sa.Column('real_time_reference', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('involved_chapters', sa.JSON(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('key_events', sa.JSON(), nullable=True),
    sa.Column('timeline_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_timelines_id'), 'story_timelines', ['id'], unique=False)
    op.create_table('style_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('style_category', sa.String(length=50), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('pace', sa.String(length=50), nullable=True),
    sa.Column('perspective', sa.String(length=50), nullable=True),
    sa.Column('applicable_scenes', sa.JSON(), nullable=True),
    sa.Column('character_specific', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_guides_id'), 'style_guides', ['id'], unique=False)
    op.create_table('style_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sample_text', sa.Text(), nullable=False),
    sa.Column('style_features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_samples_id'), 'style_samples', ['id'], unique=False)
    op.create_index(op.f('ix_style_samples_novel_id'), 'style_samples', ['novel_id'], unique=False)
    op.create_table('worldview_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('importance_level', sa.String(length=20), nullable=True),
    sa.Column('consistency_rules', sa.JSON(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_chapters', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worldview_settings_category'), 'worldview_settings', ['category'], unique=False)
    op.create_index(op.f('ix_worldview_settings_id'), 'worldview_settings', ['id'], unique=False)
    op.create_index(op.f('ix_worldview_settings_name'), 'worldview_settings', ['name'], unique=False)
    op.create_table('character_appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('appearance_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance_in_chapter', sa.Integer(), nullable=True),
    sa.Column('status_changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_appearances_id'), 'character_appearances', ['id'], unique=False)
    op.create_table('character_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('character_a_id', sa.Integer(), nullable=False),
    sa.Column('character_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('development_stage', sa.String(length=50), nullable=True),
    sa.Column('established_in_chapter', sa.Integer(), nullable=True),
    sa.Column('change_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relationships_id'), 'character_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_relationships_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_index(op.f('ix_character_appearances_id'), table_name='character_appearances')
    op.drop_table('character_appearances')
    op.drop_index(op.f('ix_worldview_settings_name'), table_name='worldview_settings')
    op.drop_index(op.f('ix_worldview_settings_id'), table_name='worldview_settings')
    op.drop_index(op.f('ix_worldview_settings_category'), table_name='worldview_settings')
    op.drop_table('worldview_settings')
    op.drop_index(op.f('ix_style_samples_novel_id'), table_name='style_samples')
    op.drop_index(op.f('ix_style_samples_id'), table_name='style_samples')
    op.drop_table('style_samples')
    op.drop_index(op.f('ix_style_guides_id'), table_name='style_guides')
    op.drop_table('style_guides')
    op.drop_index(op.f('ix_story_timelines_id'), table_name='story_timelines')
    op.drop_table('story_timelines')
    op.drop_index(op.f('ix_plot_elements_id'), table_name='plot_elements')
    op.drop_table('plot_elements')
    op.drop_index(op.f('ix_novel_outlines_id'), table_name='novel_outlines')
    op.drop_table('novel_outlines')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_user_id'), table_name='novels')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.drop_index(op.f('ix_novels_id'), table_name='novels')
    op.drop_table('novels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mcp_audit_logs_user_id'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_target_type'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_novel_id'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_id'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_created_at'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_action'), table_name='mcp_audit_logs')
    op.drop_table('mcp_audit_logs')
    # ### end Alembic commands ###
