"""story bible: 事实账本与剧情事件表

Revision ID: e6dc8b549c6d
Revises: 55198abfb01f
Create Date: 2026-08-14 19:12:12.843527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6dc8b549c6d'
down_revision: Union[str, Sequence[str], None] = '55198abfb01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('story_day', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('foreshadowing', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_events_id'), 'story_events', ['id'], unique=False)
    op.create_index(op.f('ix_story_events_novel_id'), 'story_events', ['novel_id'], unique=False)
    op.create_index(op.f('ix_story_events_status'), 'story_events', ['status'], unique=False)
    op.create_table('story_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chapter_established', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retired_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_facts_id'), 'story_facts', ['id'], unique=False)
    op.create_index(op.f('ix_story_facts_novel_id'), 'story_facts', ['novel_id'], unique=False)
    op.create_index(op.f('ix_story_facts_status'), 'story_facts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_facts_status'), table_name='story_facts')
    op.drop_index(op.f('ix_story_facts_novel_id'), table_name='story_facts')
    op.drop_index(op.f('ix_story_facts_id'), table_name='story_facts')
    op.drop_table('story_facts')
    op.drop_index(op.f('ix_story_events_status'), table_name='story_events')
    op.drop_index(op.f('ix_story_events_novel_id'), table_name='story_events')
    op.drop_index(op.f('ix_story_events_id'), table_name='story_events')
    op.drop_table('story_events')
    # ### end Alembic commands ###
